services:
  bot:
    image: joke-bot
    container_name: joke-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    tty: true
    restart: "no"
    command: python -m app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  postgres:
    image: postgres
    container_name: joke-bot-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    env_file: .env
